### ISSUE TITLE
Memory cache returns nothing

### ISSUE THREAD

**Issue by jbmaxwell** [dreymonde/Shallows#13]
I have a strange case where a `Storage.retrieve` completely skips its completion handler. The cache is composed of a MemoryStorage and a DiskStorage. I wish I could say more about it, but there's not much to say. I can see the Key go in, but the completion gets skipped entirely... ??

[EDIT: This wouldn't necessarily be a huge problem, except that I have a `DispatchGroup.leave()` waiting on the completion...]

**Comment by dreymonde** [comment]
Hi! Thanks for reaching out. Can you show some code samples if possible?

**Comment by jbmaxwell** [comment]
I should be able to add something a little later tonight.

**Comment by jbmaxwell** [comment]
Oh geez... My apologies; it looks like the disappearing completion is happening after a call to Firebase! (I have a routine that branches to check our backend if something's not found locally.) 
Google, ha! With all those billions, you think their stuff would be bullet-proof! ;-)

**Comment by dreymonde** [comment]
Haha I see. Still thanks for reaching out @jbmaxwell! Ping me if you'll have any other questions
