### ISSUE TITLE
Base64 encoding isn't great for filenames

### ISSUE THREAD

**Issue by GeorgeLyon** [dreymonde/Shallows#19]
"/" is a valid base64 character and invalid for filenames. I recommend you use Base64URL encoding. This is probably just adding the following to lines:
```
      .replacingOccurrences(of: "+", with: "-")
      .replacingOccurrences(of: "/", with: "_")
```

**Comment by dreymonde** [comment]
This is actually a very good advice. Sadly just changing it like this can be potentially breaking, so I'll have to be careful

**Comment by dreymonde** [comment]
@GeorgeLyon for now I've added `Filename.Encoding.base64URL`: https://github.com/dreymonde/Shallows/commit/cde1a3af3b4df79d0c50e1847906c236c7cd8206 (0.12.0)

I'll figure out the way to migrate the existing base64 filenames to base64URL filenames in the future
