### ISSUE TITLE
Clear object from MemoryStorage?

### ISSUE THREAD

**Issue by jbmaxwell** [dreymonde/Shallows#20]
I've been debugging some memory usage issues and just noticed/remembered that Shallows is keeping my objects in a MemoryStorage, pretty much permanently. Is there an easy way to clear objects from MemoryStorage, or clear the MemoryStorage completely?

**Comment by dreymonde** [comment]
Hi! I believe this one is relevant: https://github.com/dreymonde/Shallows/issues/11

**Comment by jbmaxwell** [comment]
Oh, geez... that's my issue, too... gulp...
(I'm a goldfish)

**Comment by dreymonde** [comment]
@jbmaxwell ahaha, that's ok. I forget everything about _my_ code five days after I write it, usually
