### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by scottcc** [dreymonde/Shallows#3]
Very nice library you have here. I see the README says one installs through Carthage, but I also see a Shallows.podspec implying (possible eventual) Cocoapods support. Is that planned, or should the .podspec be removed?

Congrats on the iOS Dev Weekly inclusion too.

**Comment by dreymonde** [comment]
Hi @scottcc! Thanks for pointing that out. I’ll add Cocoapods support ASAP 🙂

**Comment by scottcc** [comment]
Ha! Fastest response time ever @dreymonde. Nice medium writeup(s) and that Brandon Kase talk is indeed fantastic. Will be watching closely 👍.

**Comment by dreymonde** [comment]
@scottcc Thanks! I’m really glad you liked it.
I’ve published the spec. Would be grateful if you could confirm that everything works as expected now.

**Comment by zsoltmester** [comment]
I can verify that the Cocoapods support for the 0.8.1 version is working as expected.

**Comment by dreymonde** [comment]
@zsoltmester thanks!
