### ISSUE TITLE
Memory limitations and responding to warnings with combined cache? 

### ISSUE THREAD

**Issue by serendipityapps** [dreymonde/Shallows#7]
For the combined example of Memory cache with Disk Storage cache, I assume the memory cache wouldn't be cleared automatically if didReceiveMemoryWarning?  If not, I can't see a way to manually clear the memory cache.  Any suggestions? or have i missed something obvious, thanks.

**Comment by dreymonde** [comment]
Hi @serendipityapps! Thanks for reaching out.
You’re right, out-of-the-box `MemoryStorage` does not react to any system warnings. **Shallows** tries to be a very unopinionated about the logic of your app, so it doesn’t do anything behind your back. Instead, **Shallows** was designed to be able to achieve any kind of behavior easily.

First: technically, you can manually clear a `MemoryStorage` if you have a direct reference to it. There’s a mutable `storage` property which you can use:

```swift
let memoryCache = MemoryStorage<Filename, Data>()
let combined = memoryCache.combined(with: diskStorage) // Storage<Filename, Data>
// ...
memoryCache.storage = [:]
```

Second: here’s how I would make a «memory warnings aware» storage in **Shallows**:

```swift
public final class MemoryWarningsAwareMemoryStorage<Key : Hashable, Value> : StorageProtocol {
    
    public let memoryStorage: MemoryStorage<Key, Value>
    
    public init(memoryStorage: MemoryStorage<Key, Value>) {
        self.memoryStorage = memoryStorage
        self.startListening()
    }
    
    private func startListening() {
        NotificationCenter.default.addObserver(forName: .UIApplicationDidReceiveMemoryWarning,
                                               object: self,
                                               queue: nil) { (_) in
            self.memoryStorage.storage = [:]
        }
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    public func retrieve(forKey key: Key, completion: @escaping (Result<Value>) -> ()) {
        memoryStorage.retrieve(forKey: key, completion: completion)
    }
    
    public func set(_ value: Value, forKey key: Key, completion: @escaping (Result<Void>) -> ()) {
        memoryStorage.set(value, forKey: key, completion: completion)
    }
    
}

extension MemoryStorage {
    
    public func lowMemoryAware() -> Storage<Key, Value> {
        return MemoryWarningsAwareMemoryStorage(memoryStorage: self).asStorage()
    }
    
}
```

And then:

```swift
let memoryStorage = MemoryStorage<Filename, Data>().lowMemoryAware()
let combined = memoryStorage.combined(with: diskStorage)
```

Hope this helps. Let me know! 🙂

**Comment by serendipityapps** [comment]
Hey Oleg,

Thanks for quick reply and great to see your method of clearing storage was so simple 😂. 

The solution provided for memory aware memory storage also looks very useful. So much so, I wonder if this or a variant should be included in source anyway. I would think that this behaviour would probably be the default behaviour (expected?) and maybe include a flag to NOT use auto clearance if required by client?

**Comment by dreymonde** [comment]
This is a very valid point. Asking for such widely-needed feature to be included by default is, of course, reasonable. But there was a design decision when making **Shallows** to keep it very small and to the point. I don’t want to make assumptions about how developers will structure their logic. For example, if someone does not have a disk-backed solution (and the `MemoryStorage` is a single source of truth), auto clearance can be an almost impossible-to-detect bug.

**Comment by serendipityapps** [comment]
Fair enough, thanks again. 👍

**Comment by dreymonde** [comment]
You’re welcome! Ping me anytime if you'll have any questions
